### ISSUE TITLE
FAL GPL License may cause some legal issues

### ISSUE THREAD

**Issue by shihang-zhang** [armink/FlashDB#133]
Hi @armink,
Thank you for providing this amazing software. Is it possible to update the GPL license in FAL to Apache and make a release? We got a warning from this nested GPL license in the software. Thanks!

**Comment by armink** [comment]
The FAL has updated to latest version. Please try the FlashDB latest version code.

**Comment by bethmal** [comment]
Hi @armink ,

Will there be an official release against this update? Thanks!

**Comment by armink** [comment]
The official version will be released in April.

**Comment by armink** [comment]
Hi, The FlashDB has released V1.1.2
