### ISSUE TITLE
Block Size small results in LIB_SAVED_FULL

### ISSUE THREAD

**Issue by T721** [armink/FlashDB#140]
I have a question regarding the block size to which i did not find the answer in the examples to.
We use FlashDB on a raw RAM memory block so block size is not really a thing here. 
When i set Block Size to like 64Bytes i only can store 1 value in a 8kB sized memory block before the lib allways returns SAVED_FULL.
Why is that? there are plenty of blocks of free memory remaining in that 8K Memory

here follows my config:
![image](https://user-images.githubusercontent.com/36440038/162388507-3015fd4b-e96c-41e8-99b3-08ddc7e6b44c.png)
![image](https://user-images.githubusercontent.com/36440038/162388681-2d03f06e-0e75-45da-b6d6-90076d90a401.png)

**Comment by T721** [comment]
i might have a solution to my Problem myself. Block size needs to be bigger (actually by 1) than the keysize. This might be quite obvious but for me it was not yet clear.

**Comment by TobeyWins** [comment]
closed
