### ISSUE TITLE
Compile Error when not using FDB_KV_USING_CACHE 

### ISSUE THREAD

**Issue by T721** [armink/FlashDB#142]
Hi @armink 

when FDB_KV_USING_CACHE is undefined to avoid caching of elements there is a compile error in fdb_kvdb.c:1486
in function check_and_recovery_kv_cb, where the following is used:

![image](https://user-images.githubusercontent.com/36440038/163003691-a5c6ea6e-b224-462d-b265-150b7eafe809.png)

how can this be solved?

**Comment by T721** [comment]
This is my temporary solution, as the check is only performed in startup.
Another option would be to also guard the method call with the defines but i'm not sure about side effects.
Anyone had the same problem?
![image](https://user-images.githubusercontent.com/36440038/163005030-1e016335-70cf-47b0-92b8-8c47f36dad41.png)

**Comment by armink** [comment]
Yes, FDB_KV_USING_CACHE cannot be disable at this time. Why do you want to disable it?

**Comment by T721** [comment]
im using it on multiple cores/instances and do not want to deinit/init everytime. When i cache the elements and edit the same stuff on another instance, i need to deinit / init the first instance beforehand so there is not old data present.
For this reason i do not want to use chaching and set the following in fdb_cfg.h

![image](https://user-images.githubusercontent.com/36440038/163107353-bfecc52b-d287-4124-93f5-0295027ac651.png)

which disables the following

![image](https://user-images.githubusercontent.com/36440038/163107393-ed8a0a43-e78a-4c83-812d-1883175a9360.png)

**Comment by armink** [comment]
Yes, would you like to fix this.

**Comment by T721** [comment]
Hi @armink,
sure, i can have a look at this next week.

**Comment by armink** [comment]
👍

**Comment by armink** [comment]
You can fork first. Then start a PR from your repository.
