### ISSUE TITLE
建议kv初始化的时候，不对删除状态的数据进行处理

### ISSUE THREAD

**Issue by chwncy** [armink/FlashDB#157]
由于kv在初始化的时候，会对所有数据进行检验，如果flash中保存都是重复数据，建议不对删除状态的数据进行校验，以减少初始化的时间。

因此，我在“read_kv”函数中添加了以下代码：
![flashdb](https://user-images.githubusercontent.com/31879464/173774620-a76338f3-9d77-40d0-95c5-618fd7b1a7b1.png)

**Comment by armink** [comment]
好想法，方便提交一下 PR 吗？

**Comment by chwncy** [comment]
可以的

发自我的iPhone

在 2022年6月15日，18:21，朱天龙 (Armink) ***@***.***> 写道：

﻿

好想法，方便提交一下 PR 吗？
