### ISSUE TITLE
KVD模式，如果GC过程中设备掉电，会产生数据损坏吗？新数据未能完成写入不要紧，关键是老数据是否会破损。

### ISSUE THREAD

**Issue by hongxiong** [armink/FlashDB#186]
@armink 
KVD模式，如果GC过程中设备掉电，会产生数据损坏吗？新数据未能完成写入不要紧，关键是老数据是否会破损。
项目中使用，这里是个关键指标，谢谢！

**Comment by armink** [comment]
- 新数据不保
- 老数据是安全的

**Comment by hongxiong** [comment]
感谢迅速的回应！这也是我的预期，多谢。
