### ISSUE TITLE
fdb_kv_iterate never return false

### ISSUE THREAD

**Issue by GiulioDallaVecchia** [armink/FlashDB#211]
fdb_kv_iterate function never return false even after that all sectors are checked

**Comment by armink** [comment]
Is it an issue with the latest version? Can you go into more detail?

**Comment by GiulioDallaVecchia** [comment]
Hi @armink,

I'm referring to the last commit on the master branch.

Thanks!

**Comment by armink** [comment]
Ok, thanks for your feedback, I'll fix it today

**Comment by armink** [comment]
you can test in the latest commit
