### ISSUE TITLE
 install Flash DB on ESP32

### ISSUE THREAD

**Issue by Yukselzngn** [armink/FlashDB#231]
Hi Armink,
Can you please give me details how to install Flash DB on ESP32

**Comment by armink** [comment]
you can see ESP demo https://github.com/armink/FlashDB/tree/master/demos/esp32_spi_flash

**Comment by Yukselzngn** [comment]
Thank you for your answer.
I applied the database as in the example, but it gives this error while building.
../components/dbsrc/fal_flash_esp32_port.c:8:10: fatal error: esp_partition.h: No such file or directory
     8 | #include <esp_partition.h>
       | ^~~~~~~~~~~~~~~~~
compilation terminated.

When I check the file exists and is defined but it gives this error.

**Comment by Yukselzngn** [comment]
FlashDB ESP32 SPI Flash Demo
This is ESP32 chip with 2 CPU cores, WiFi, silicon revision 300, [I/FAL] Flash Abstraction Layer (V0.5.99) initialize success.

assert failed: esp_partition_read partition_target.c:29 (partition != NULL)

ı have this error
