### ISSUE TITLE
flashdb日志写满判断

### ISSUE THREAD

**Issue by Nekomiya-fubuki** [armink/FlashDB#261]
您好，我现在使用的是esp32的demo例程，运行在esp32s3的板卡上。我有几个问题想要请教下
1.数据库的数据是会存储到esp32的spi flash上面么
2.我现在在不停地写入flashdb数据，我该如何知道日志已经被写满了
3.我是否有方法可以检测我设定存储分区是否已经被flashdb存储的数据占用满了呢

**Comment by armink** [comment]
现在还没有办法通知，但你可以通过 tsl_append 的返回值来识别

**Comment by Nekomiya-fubuki** [comment]
好的谢谢。然后现在又产生了一个问题，就是我给日志设置了禁止滚动写入，flashdb固定写到第676个数据的时候就显示已经saved_full。我该如何增加写入的容量呢
