### ISSUE TITLE
出现crc32 failed, 测试程序boot_count总是读取失败, 但是测试程序temp的read/write是正常的

### ISSUE THREAD

**Issue by graydonli** [armink/FlashDB#270]
使用的master分支, 现在的最新版本, boot_count和temp的读取和写入都出现(bo@0x00000014) CRC32 check failed!  , 但是boot_count的写入返回值是成功的, temp的读写都成功

**Comment by graydonli** [comment]
FlashDB仅支持1/8/32/64bit的写入最小单元, 如果主控的写操作一次性超过这样的数据量需要适配

**Comment by graydonli** [comment]
FlashDB仅支持1/8/32/64bit的写入最小单元, 如果主控的写操作一次性超过这样的数据量需要适配

**Comment by jaytang0923** [comment]
> FlashDB仅支持1/8/32/64bit的写入最小单元, 如果主控的写操作一次性超过这样的数据量需要适配

我也遇到这种问题，但是你这个解决是什么意思？单次只能按照最小单元操作写？
