### ISSUE TITLE
sfud_flash_def.h 部分有误

### ISSUE THREAD

**Issue by novolife** [armink/FlashDB#283]
`#define SFUD_MF_ID_MICRONIX                            0xC2`

应为

`#define SFUD_MF_ID_MACRONIX                            0xC2`

没有MICRONIX这家Flash公司，可能是与MICRON混淆了，其他地方也需要修改

**Comment by armink** [comment]
![image](https://github.com/armink/FlashDB/assets/1734686/0a09d5fb-c7a7-4f82-b9c2-1f1ab471d53b)

**Comment by novolife** [comment]
是的，应该是 **M _A_ CRONIX**，我手头 Macronix 的 datasheet 里`Manufacturer ID`就是`0xC2`

**Comment by armink** [comment]
👍 可以给 https://github.com/armink/SFUD 提交 PR 哈

**Comment by novolife** [comment]
看起来那边两年前修正了，应该是这边的demo没有更新😊
