### ISSUE TITLE
FlashDB Error  请教一下怎么回事？

### ISSUE THREAD

**Issue by jlmhkzj** [armink/FlashDB#30]
\ | /
- RT -     Thread Operating System
 / | \     3.1.3 build Sep 21 2020
 2006 - 2019 Copyright by rt-thread team
SPI2 DWM1000 Attach Success!
spi2 run success! can find spi20_dem1000 device!
spi2 Configure Success!
DeviceID = DECA0130
DWM1000 Init Scccess!
[SFUD] Find a Winbond flash chip. Size is 2097152 bytes.
[SFUD] FLASH_W25Q16 flash device is initialize success.
[D/FAL] (fal_flash_init:61) Flash device |             stm32_onchip | addr: 0x08000000 | len: 0x00100000 | blk_size: 0x00020000 |initialized finish.
[D/FAL] (fal_flash_init:61) Flash device |             FLASH_W25Q16 | addr: 0x00000000 | len: 0x00200000 | blk_size: 0x00001000 |initialized finish.
[I/FAL] ==================== FAL partition table ====================
[I/FAL] | name      | flash_dev    |   offset   |    length  |
[I/FAL] -------------------------------------------------------------
[I/FAL] | app       | stm32_onchip | 0x00000000 | 0x00100000 |
[I/FAL] | fdb_tsdb1 | FLASH_W25Q16 | 0x00000000 | 0x00000400 |
[I/FAL] | fdb_kvdb1 | FLASH_W25Q16 | 0x00000400 | 0x00000400 |
[I/FAL] =============================================================
[I/FAL] RT-Thread Flash Abstraction Layer (V0.5.0) initialize success.
[FlashDB][kv][env] (packages\FlashDB-latest\src\fdb_kvdb.c:1583) ((FDB_GC_EMPTY_SEC_THRESHOLD > 0 && FDB_GC_EMPTY_SEC_THRESHOLD < SECTOR_NUM)) has assert failed at fdb_kvdb_init.

**Comment by armink** [comment]
这里的断言检查条件没有过
