### ISSUE TITLE
Is wear balance/leveling implemented ?

### ISSUE THREAD

**Issue by bogdanm** [armink/FlashDB#309]
While the README specifies "supports wear balance", a quick grep for "wear" through the sources only shows some configuration options for the ESP32 demo. Is wear leveling already implemented in the main FlashDB code or is this a port-specific implementation option? Thank you.

**Comment by armink** [comment]
Yes

**Comment by bogdanm** [comment]
I'm going to assume that you mean "yes, it is implemented", not "yes, it is a port-specific implementation option". Thank you.

**Comment by armink** [comment]
yes, it is implemented :>
