### ISSUE TITLE
FlashDB是否可以将一个数据进行跨扇区存储？

### ISSUE THREAD

**Issue by littlewhitezkz** [armink/FlashDB#323]
KVDB扇区头结构的combine的作用是指向分割的数据的偏移地址？是否该功能意味着可以把数据存一部分在一个扇区，将另一部分存入别的扇区，保留下一个扇区的偏移地址即可。

**Comment by armink** [comment]
combine 模式还未支持

**Comment by littlewhitezkz** [comment]
> combine 模式还未支持

感谢朱工，处于好奇问一下，这一模式没有实装是因为何种技术问题，可以分享一下吗

**Comment by armink** [comment]
没时间，需求也少哈
