### ISSUE TITLE
构建结构不合理

### ISSUE THREAD

**Issue by ShunzDai** [armink/FlashDB#336]
1. log_i log_w 可能与其他模块的日志宏冲突
2. fdb_cfg.h 不应当与其他头文件位于同一个目录, 而应当位于一个独立的config模板目录, 否则用户无法将此模块作为子模块融入自己的工程, 用户自己的fdb_cfg.h会与inc路径下的fdb_cfg.h冲突
3. fal_flash_dev应该加入fal_partition中作为成员变量, 硬件抽象层将fal_partition传入port接口, port从fal_partition中拿取硬件抽象层接口进行flash操作

**Comment by armink** [comment]
先看下问题2 
> 用户自己的fdb_cfg.h会与inc路径下的fdb_cfg.h冲突

这个问题可否看下 demos 工程里的做法？不同项目下，配置不一样都可以正常使用的


其他两个问题，算是 FAL 的问题了，log 的问题好推进去更新，第三个问题没有太看懂呢

**Comment by armink** [comment]
可以的，问题2，要不你来改一下？
