### ISSUE TITLE
支持带Offset方式读取和写入

### ISSUE THREAD

**Issue by wireless-guy** [armink/FlashDB#34]
朱工，你好，
问下后续是否有计划支持带Offset方式对某个kv对进行读取和写入。
谢谢。

**Comment by armink** [comment]
没有太明白你的需求，可否详细举例说明一下

**Comment by wireless-guy** [comment]
比方说我在EasyFlash里面存了一个结构体数组a[100]，每个数组元素a[]是一个结构体，我想从Flash读取a[50]的内容，我不需要把整个a[0]~a[100]读出来，可以通过偏移量的方式直接读取a[50]的内容.

**Comment by armink** [comment]
FlashDB 如何知道 a[50] 的偏移地址，并返回给用户呢？

**Comment by wireless-guy** [comment]
用户通过参数输入，比方说50*单个结构体长度，存放的变量也是用输入。

**Comment by armink** [comment]
有个比较粗暴的方法，可以试试

- 获取到 kv 对象，得到 kv 偏移地址 https://armink.github.io/FlashDB/#/zh-cn/api?id=%e8%8e%b7%e5%8f%96-kv-%e5%af%b9%e8%b1%a1
- 通过 `_fdb_flash_read` API 来读取

**Comment by wireless-guy** [comment]
这样的话需要外部提供一个很大的局部变量或者全局变量来暂存数据吧？

**Comment by armink** [comment]
不用的，_fdb_flash_read 本身就是可以直接基于 offset 来读取
