### ISSUE TITLE
flashdb   如何修改删除  

### ISSUE THREAD

**Issue by hcb900330** [armink/FlashDB#4]
数据库的修改删除如何操作   

还有fdb_tsl_query_count(tsdb, from_time, to_time,FDB_TSL_USER_STATUS1);  这个函数返回的数据也是错的

**Comment by armink** [comment]
删除可以参考 sample 里的示例，修改 TSL 的状态就好了

时序的历史数据一般生成了，目前是无法再次修改的，除非删除
