### ISSUE TITLE
每次启动日志都提示 [FlashDB][kv][env] Found an KV (user_setting) which has changed value failed. Now will recovery it.

### ISSUE THREAD

**Issue by qinhao4832** [armink/FlashDB#48]
\ | /
- RT -     Thread Operating System
 / | \     4.0.3 build Dec 18 2020
 2006 - 2020 Copyright by rt-thread team
spi1 GPIO_PinsRemapConfig = AFIO_MAP5_SPI1_0001
[I/SFUD] Find a Winbond flash chip. Size is 4194304 bytes.
[I/SFUD] sf_cmd flash device is initialize success.
[I/SFUD] Probe SPI flash sf_cmd by SPI device SPI_flash success.
4 MB sf_cmd is current selected device.
[I/FAL] Flash Abstraction Layer (V0.5.0) initialize success.
[FlashDB][kv][env] (../../../components/FlashDB/src/fdb_kvdb.c:1599) KVDB in partition fdb_kvdb1, size is 32768 bytes.
[FlashDB][kv][env] Found an KV (user_setting) which has changed value failed. Now will recovery it.
msh >msh >

 \ | /
- RT -     Thread Operating System
 / | \     4.0.3 build Dec 18 2020
 2006 - 2020 Copyright by rt-thread team
spi1 GPIO_PinsRemapConfig = AFIO_MAP5_SPI1_0001
[I/SFUD] Find a Winbond flash chip. Size is 4194304 bytes.
[I/SFUD] sf_cmd flash device is initialize success.
[I/SFUD] Probe SPI flash sf_cmd by SPI device SPI_flash success.
4 MB sf_cmd is current selected device.
[I/FAL] Flash Abstraction Layer (V0.5.0) initialize success.
[FlashDB][kv][env] (../../../components/FlashDB/src/fdb_kvdb.c:1599) KVDB in partition fdb_kvdb1, size is 32768 bytes.
[FlashDB][kv][env] Found an KV (user_setting) which has changed value failed. Now will recovery it.
msh >msh >psr: 0x21000053
r00: 0x50001000
r01: 0x20000102
r02: 0x00000001
r03: 0x00000004
r04: 0x20001a68
r05: 0x00000004
r06: 0x00000001
r07: 0x00000000
r08: 0x20001b9c
r09: 0x20001b90
r10: 0x20001b98
r11: 0x20001a80
r12: 0x00000000
 lr: 0x08008e85
 pc: 0x0800a03a
hard fault on handler

usage fault:
SCB_CFSR_UFSR:0x100 UNALIGNED

**Comment by armink** [comment]
看着像 flash 驱动问题
