### ISSUE TITLE
iar编译flashdb时报错：argument of type "void (*)(fdb_db_t)" is incompatible with parameter of type "void *" 

### ISSUE THREAD

**Issue by Roger-WY** [armink/FlashDB#51]
朱工，您好：
之前用MDK测试FlashDB效果很好，同样的源文件，添加到IAR创建的工程时，编译报错，
‘ argument of type "void (*)(fdb_db_t)" is incompatible with parameter of type "void *" ’
具体如下图所示：
![image](https://user-images.githubusercontent.com/20040119/103270371-abe8b500-49f2-11eb-8f7e-960c5dce31d1.png)

mdk编译能通过并正常运行，麻烦朱工帮忙看下什么问题，谢谢！

**Comment by armink** [comment]
强制类型转换一下试试？

**Comment by Roger-WY** [comment]
感谢朱工的回复，加上强制转换就不报错了！
`
/* set the lock and unlock function if you want */
fdb_tsdb_control(&tsdb, FDB_TSDB_CTRL_SET_LOCK, (void *)lock);
fdb_tsdb_control(&tsdb, FDB_TSDB_CTRL_SET_UNLOCK, (void *)unlock);
`

**Comment by armink** [comment]
方便提个 PR 上来不

**Comment by Roger-WY** [comment]
好的 我整理一下 我这边是基于STM32F103标准库测试的。
