### ISSUE TITLE
#if (KV_STATUS_TABLE_SIZE >= FDB_DIRTY_STATUS_TABLE_SIZE) may not work as expected

### ISSUE THREAD

**Issue by ivan7wl** [armink/FlashDB#60]
In `fdb_kvdb.c::del_kv()` function, `FDB_SECTOR_STORE_STATUS_NUM` and `FDB_SECTOR_DIRTY_STATUS_NUM` is an enum constant, if used in #if statement, the preprocessor will assume they are undefined macros, and evaluate to 0, so the #if statement will always be true.
Suggest use:
```
uint8_t status_table[KV_STATUS_TABLE_SIZE >= FDB_DIRTY_STATUS_TABLE_SIZE ? KV_STATUS_TABLE_SIZE : DIRTY_STATUS_TABLE_SIZE];
```

在`fdb_kvdb.c::del_kv()`函数中，`FDB_SECTOR_STORE_STATUS_NUM`和`FDB_SECTOR_DIRTY_STATUS_NUM`是枚举常量，在#if条件编译语句中，预处理器将它们看作是未定义的宏，求值为0，#if语句永远为真。
建议使用：
```
uint8_t status_table[KV_STATUS_TABLE_SIZE >= FDB_DIRTY_STATUS_TABLE_SIZE ? KV_STATUS_TABLE_SIZE : DIRTY_STATUS_TABLE_SIZE];
```

**Comment by AdrianGuo** [comment]
咋不提价PR呢

**Comment by armink** [comment]
两种方式都可以的，各有利弊，还可定义一个 MAX 宏来进一步简化

```
uint8_t status_table[KV_STATUS_TABLE_SIZE >= FDB_DIRTY_STATUS_TABLE_SIZE ? KV_STATUS_TABLE_SIZE : DIRTY_STATUS_TABLE_SIZE];
```

```C
#if (KV_STATUS_TABLE_SIZE >= FDB_DIRTY_STATUS_TABLE_SIZE)
    uint8_t status_table[KV_STATUS_TABLE_SIZE];
#else
    uint8_t status_table[DIRTY_STATUS_TABLE_SIZE];
#endif
```

**Comment by ivan7wl** [comment]
> 两种方式都可以的，各有利弊，还可定义一个 MAX 宏来进一步简化
> 
> ```
> uint8_t status_table[KV_STATUS_TABLE_SIZE >= FDB_DIRTY_STATUS_TABLE_SIZE ? KV_STATUS_TABLE_SIZE : DIRTY_STATUS_TABLE_SIZE];
> ```
> 
> ```c
> #if (KV_STATUS_TABLE_SIZE >= FDB_DIRTY_STATUS_TABLE_SIZE)
>     uint8_t status_table[KV_STATUS_TABLE_SIZE];
> #else
>     uint8_t status_table[DIRTY_STATUS_TABLE_SIZE];
> #endif
> ```

用#if条件编译，实际求值的是
```
#if FDB_STATUS_TABLE_SIZE(0) >= FDB_STATUS_TABLE_SIZE(0)
```
而不是预期的
```
#if FDB_STATUS_TABLE_SIZE(6) >= FDB_STATUS_TABLE_SIZE(4)
```

**Comment by armink** [comment]
其实我的预期也不是 

```
#if FDB_STATUS_TABLE_SIZE(6) >= FDB_STATUS_TABLE_SIZE(4)
```

应该会根据 Flash 的写粒度，自动计算出实际占用的字节数，比如：当写粒度为 1 时

![image](https://user-images.githubusercontent.com/1734686/105286482-57031d80-5bf1-11eb-824e-03b7dedb8c14.png)

**Comment by ivan7wl** [comment]
> 其实我的预期也不是
> 
> ```
> #if FDB_STATUS_TABLE_SIZE(6) >= FDB_STATUS_TABLE_SIZE(4)
> ```
> 
> 应该会根据 Flash 的写粒度，自动计算出实际占用的字节数，比如：当写粒度为 1 时
> 
> ![image](https://user-images.githubusercontent.com/1734686/105286482-57031d80-5bf1-11eb-824e-03b7dedb8c14.png)

问题是预处理器只认识宏定义啊，用-Wundef参数编译一下就看到了

**Comment by armink** [comment]
👍 感谢你的反馈哈，已修正
