### ISSUE TITLE
关于tsdb和kvdb的如何备份和恢复的方法

### ISSUE THREAD

**Issue by illusionkiller** [armink/FlashDB#75]
朱工，您好，请问现在这两种数据库支持简单的备份和恢复吗，比如说我想把当前的数据库信息备份一下，以便需要用的时候进行恢复（目前我的做法比较笨，直接复制整个数据库所在的分区，也能使用，但是总感觉这样做不太好，因为板子目前不支持文件系统，不然的话也可以考虑直接复制文件），请问朱工有什么好的解决方法吗？

**Comment by armink** [comment]
复制文件、复制分区这种方法挺简单的，不太理解，你觉得哪里不够好呢 :>

**Comment by illusionkiller** [comment]
缺点就是如果采用这种整个分区复制的方法，如果给定的分区比较大的话，复制的时间会比较长，出现错误的可能性就比较大
