### ISSUE TITLE
KVDB 修改版本号后，默认值不会更新

### ISSUE THREAD

**Issue by fishjimi** [armink/FlashDB#79]
已经输出类似 Update the KV from version 1 to 2 这样的日志

但是用samples里的测试代码， boot_count读出来还是上次写入的那个。
即使我把默认值改成别的，修改版本号后 也没用

**Comment by armink** [comment]
除非你本地没有默认 boot_count 了才会更新为默认

策略是，如果默认表里有的，但是本地没有的才会更新
