### ISSUE TITLE
关于NAND-FLASH坏块

### ISSUE THREAD

**Issue by GitHubForPP** [armink/FlashDB#92]
您好，我想问问，FlashDB在写入时序数据时写入了坏块扇区里了，是否影响后续写入？还是写入会持续，只是坏块部分写入就丢失了？

**Comment by armink** [comment]
目前还不支持 nandflash

**Comment by GitHubForPP** [comment]
> 目前不支持nandflash

有没有支持nandflash的管理系统推荐呀，咱们这边有计划支持nandflash吗？

**Comment by armink** [comment]
这块还没有计划的
